### ISSUE TITLE
Call to undefined method WP_CLI_Pre_Cache_Command::_read()

### ISSUE THREAD

**Issue by sebastiaandegeus** [runcommand/precache#1]
Is this completely missing?

**Comment by danielbachhuber** [comment]
Yeah, copy and paste bug

**Comment by fortitude-it** [comment]
Any update on this? I'm receiving this message also, and would really love to use this precache feature

**Comment by fortitude-it** [comment]
(Sorry if this isn't warranted here, I'm still a github n00b) I just wanted to say thanks!

**Comment by danielbachhuber** [comment]
> (Sorry if this isn't warranted here, I'm still a github n00b) I just wanted to say thanks!

Not at all — happy to help!
