### ISSUE TITLE
cant install package

### ISSUE THREAD

**Issue by chrismccoy** [runcommand/precache#11]
running WP-CLI 0.24.0-alpha-8adaf46

```
chris@golf:~$ wp package install runcommand/precache
Installing runcommand/precache (dev-master)
Updating /home/chris/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...

---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.257 seconds
Your requirements could not be resolved to an installable set of packages.
Problem 1
- The requested package runcommand/precache could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

---
Error: Package installation failed (Composer return code 2). Reverted composer.json
```

this has happened with a bunch of packages, all the runcommand ones, etc and a few other that have a github repo, but still get the same error.

**Comment by danielbachhuber** [comment]
This is actually an issue with WP-CLI itself, unfortunately :( I haven't had a chance to dive into it to see if I can figure out a way to reliably reproduce it, but at least now we have an issue for it: https://github.com/wp-cli/wp-cli/issues/3058

When it happened to me, I was able to get around it by deleting the entire `~/.wp-cli/packages` directory, which is unfortunate I know. You may also be able to just delete the Composer cache with the bad data.

**Comment by masterut** [comment]
chris please return me money what you own me 1200$

**Comment by danielbachhuber** [comment]
@mastercut I'm not sure who you're trying to get ahold of, but this isn't the appropriate place to do so.

**Comment by masterut** [comment]
thats for chrismccoy, sorry he ignore email but here is active
