### ISSUE TITLE
Call to undefined function download_url()

### ISSUE THREAD

**Issue by sebastiaandegeus** [runcommand/precache#2]
When I implemented file_get_contents in get_core_download_offer to circumvent the error in _read method missing. I still get this error. 

There is no function download_url()

**Comment by sebastiaandegeus** [comment]
Ah, this is a wordpress function. Maybe find an alternative if this command will be made to run before a wp installation is present.

**Comment by danielbachhuber** [comment]
WP-CLI uses `Requests` behind the scenes: https://github.com/wp-cli/wp-cli/blob/master/php/commands/core.php#L67

We could update this package to do the same. Up for putting together a pull request?
